version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
      # - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase  # URL подключения к БД

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: devops_app_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
