# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Настройка PostgreSQL сервиса
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app_admin
          POSTGRES_PASSWORD: pswd
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # Устанавливаем переменные окружения для подключения к базе
      DATABASE_URL: postgresql://app_admin:pswd@localhost:5432/test_db

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run migrations
        run: |
          alembic upgrade head  # или другой инструмент миграции, если используете

      - name: Run tests
        env:
          # Устанавливаем URL базы для тестов
          DATABASE_URL: postgresql://user:password@localhost:5432/test_db
        run: |
          pytest